### ISSUE TITLE
Auto-fill name if commit-id is given with run-name and commit-id

### ISSUE THREAD

**Issue by ucyo** [sqsh-project/hypcmp#13]
https://github.com/sqsh-project/hypcmp/blob/aa2b86df882344e6ed2231a8def1eee335230e08/src/core.rs#L49

If there is the following example of a toml configuration file

```toml
hyperfine_params = [  # common hyperfine parameters for all runs
    "--runs", "5",
    "--warmup", "3",
    "--parameter-list", "ifile", "Cargo.toml,README.md",
    "--parameter-list", "ofile", "/tmp/test.raw",
]

[run.dd]
commits = ["main", "e24af21"] # can be hash, tag or branch
command = "dd if={ifile} of={ofile}"
cleanup = "rm {ofile}"

[run.cp]
commits = ["main"]
command = "cp {ifile} {ofile}"
name = "copy"

[run.rsync]
command = "rsync -a {ifile} {ofile}"

[run.rsync2]
command = "rsync -a {ifile} {ofile}"
name = "rsync2"
```

Cases:
1. No name & commits (like `dd`): Could be `dd@e24af21` and `dd@main`.
2. No name & no commits (like `rsync`): Naming could be `rsync`.
3. Name & commits (like `cp`): Naming could be `cp@main`.
4. Name & no commits (like `rsync2`): Naming could be `rsync2` **watch out for collisions with case 2**.

Solutions:
1. Remove the naming attribute and use run names. This would eliminate case 1&2 and only leave 3&4. No ambiguity.
